.PHONY: clean All

All:
	@echo "----------Building project:[ juegocpp - Debug ]----------"
	@"$(MAKE)" -f  "juegocpp.mk"
clean:
	@echo "----------Cleaning project:[ juegocpp - Debug ]----------"
	@"$(MAKE)" -f  "juegocpp.mk" clean
