/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: c:\Documents and Settings\Juanma\Mis documentos\Proyectos\VC\Juego\sprites.dat */
/* Date: Mon Dec 25 02:40:53 2006 */
/* Do not hand edit! */

#define SPRITES                          0        /* PAL  */
#define cartel_1                         1        /* BMP  */
#define cuchara                          2        /* BMP  */
#define dragon_1                         3        /* BMP  */
#define dragon_2                         4        /* BMP  */
#define dragon_3                         5        /* BMP  */
#define espada_h                         6        /* BMP  */
#define espada_v                         7        /* BMP  */
#define estrella                         8        /* BMP  */
#define EVERSOFT                         9        /* BMP  */
#define extra                            10       /* BMP  */
#define garrote                          11       /* BMP  */
#define granada                          12       /* BMP  */
#define gusano_1                         13       /* BMP  */
#define gusano_2                         14       /* BMP  */
#define gusano_3                         15       /* BMP  */
#define hueso_horz                       16       /* BMP  */
#define hueso_incl                       17       /* BMP  */
#define hueso_vert                       18       /* BMP  */
#define jugador_01                       19       /* BMP  */
#define jugador_02                       20       /* BMP  */
#define jugador_03                       21       /* BMP  */
#define jugador_04                       22       /* BMP  */
#define jugador_05                       23       /* BMP  */
#define jugador_06                       24       /* BMP  */
#define jugador_07                       25       /* BMP  */
#define jugador_08                       26       /* BMP  */
#define jugador_09                       27       /* BMP  */
#define jugador_10                       28       /* BMP  */
#define jugador_11                       29       /* BMP  */
#define jugador_12                       30       /* BMP  */
#define jugador_13                       31       /* BMP  */
#define jugador_14                       32       /* BMP  */
#define jugador_15                       33       /* BMP  */
#define jugador_16                       34       /* BMP  */
#define jugador_17                       35       /* BMP  */
#define jugador_18                       36       /* BMP  */
#define jugador_19                       37       /* BMP  */
#define jugador_20                       38       /* BMP  */
#define jugador_21                       39       /* BMP  */
#define jugador_22                       40       /* BMP  */
#define jugador_23                       41       /* BMP  */
#define jugador_24                       42       /* BMP  */
#define jugador_25                       43       /* BMP  */
#define jugador_26                       44       /* BMP  */
#define Letra_A                          45       /* BMP  */
#define Letra_C                          46       /* BMP  */
#define Letra_E                          47       /* BMP  */
#define Letra_H                          48       /* BMP  */
#define Letra_L                          49       /* BMP  */
#define Letra_O                          50       /* BMP  */
#define Letra_P                          51       /* BMP  */
#define Letra_R                          52       /* BMP  */
#define Letra_S                          53       /* BMP  */
#define Letra_V                          54       /* BMP  */
#define loro_1                           55       /* BMP  */
#define loro_2                           56       /* BMP  */
#define loro_3                           57       /* BMP  */
#define martillo                         58       /* BMP  */
#define oro                              59       /* BMP  */
#define oso_1                            60       /* BMP  */
#define oso_2                            61       /* BMP  */
#define oso_3                            62       /* BMP  */
#define patata_1                         63       /* BMP  */
#define patata_2                         64       /* BMP  */
#define pera                             65       /* BMP  */
#define puntos_200                       66       /* BMP  */
#define puntos_20mil                     67       /* BMP  */
#define semaforo_go                      68       /* BMP  */
#define semaforo_stop                    69       /* BMP  */
#define suelo_1                          70       /* BMP  */
#define suelo_2                          71       /* BMP  */
#define tomate                           72       /* BMP  */
#define demon                            73       /* BMP  */
#define uvas                             74       /* BMP  */
#define AYUDA                            75       /* TXT  */
#define disparo                          76       /* SAMP */
#define rebote                           77       /* SAMP */
#define recogida                         78       /* SAMP */

