name: 'test'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:

  # ==============================
  # COMPILACIÓN EN UBUNTU
  # ==============================
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y build-essential liballegro4-dev
      - name: Build juegocpp (Linux)
        run: |
          cd Clases
          make
          make install
          cd ..
          mkdir -p juegocpp
          mv Extras/juegocpp juegocpp/
      - uses: actions/upload-artifact@v4
        with:
          name: juegocpp-linux
          path: juegocpp


  # ==============================
  # COMPILACIÓN EN WINDOWS / MSYS2
  # ==============================
  windows:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW32, runner: windows-2022 },
          { msystem: MINGW64, runner: windows-2022 },
          { msystem: UCRT64,  runner: windows-2022 },
        ]
    name: ${{ matrix.msystem }}
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: temp
          fetch-depth: 0
          persist-credentials: false

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            git
            base-devel
            unzip
            wget
            mingw-w64-${{ matrix.msystem == 'MINGW32' && 'i686' || (matrix.msystem == 'MINGW64' && 'x86_64' || 'ucrt-x86_64') }}-gcc
          update: true

      - name: "Compile project with Allegro 4.4.2"
        shell: msys2 {0}
        run: |
          set -e
          wget -q http://cdn.allegro.cc/file/library/allegro/4.4.2/allegro-4.4.2-mingw-4.4.0.zip
          unzip -q allegro-4.4.2-mingw-4.4.0.zip
          unzip -q temp/test-allegro4.2.zip
          cd juegocpp-test-allegro4.2/Clases
          for f in *.cpp; do
            g++.exe -Wall -O2 -I../../allegro-4.4.2-mingw-4.4.0/include -c $f -o ${f%.cpp}.o
          done
          g++.exe -s -static -static-libgcc -static-libstdc++ \
            -L../../allegro-4.4.2-mingw-4.4.0/lib \
            -o ../Extras/test_juego.exe *.o \
            ../../allegro-4.4.2-mingw-4.4.0/lib/liballegro-4.4.2-monolith-md-debug.a
          echo "Build complete:"
          ls -lh ../Extras

      - name: "Package clean ZIP (no system DLLs)"
        shell: msys2 {0}
        run: |
          cd juegocpp-test-allegro4.2/Extras
          cp ../../allegro-4.4.2-mingw-4.4.0/bin/allegro-4.4.2-monolith-md-debug.dll . 2>/dev/null || true
          zip -r9 ../Extras_${MSYSTEM}.zip ./*
          sha256sum ../Extras_${MSYSTEM}.zip > ../Extras_${MSYSTEM}.sha256
          echo "ZIP and hash created:"
          ls -lh ../Extras_${MSYSTEM}*

      - name: "Upload ZIP artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.msystem }}-build
          path: |
            juegocpp-test-allegro4.2/Extras_${{ matrix.msystem }}.zip
            juegocpp-test-allegro4.2/Extras_${{ matrix.msystem }}.sha256
