name: Build with MSYS2

on:
  push:
    branches:
      - dev-editor
  pull_request:
    branches:
      - dev-editor

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW32

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >
          mingw-w64-i686-toolchain
          make
          unzip
          wget

    - name: Add MSYS2 to PATH
      run: echo "C:\\msys64\\mingw32\\bin;${{ env.PATH }}" >> $GITHUB_PATH
      
    - name: List files for debugging
      run: |
            ls -R Clases/GUI
            which g++
            g++ --version


    - name: "Compile project with Allegro 4.4.2 (static)"
      shell: msys2 {0}
      run: |
            set -e
            wget -q http://cdn.allegro.cc/file/library/allegro/4.4.2/allegro-4.4.2-mingw-4.5.2.zip
            unzip -q allegro-4.4.2-mingw-4.5.2.zip

    - name: Build with make in Clases/GUI
      shell: bash
      run: |
        cd Clases/GUI
        make

    - name: "Upload ZIP artifact"
      uses: actions/upload-artifact@v4
      with:
          name: Win32-MinGw-build-test
          path: |
            Win32-MinGw-build-test.zip
            Win32-MinGw-build-test.sha256




