name: Build with MSYS2

on:
  push:
    branches:
      - dev-editor
  pull_request:
    branches:
      - dev-editor

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW32

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >
          mingw-w64-i686-toolchain
          mingw-w64-i686-SDL2
          mingw-w64-i686-SDL2_mixer
          mingw-w64-i686-SDL2_ttf
          make
          zip
          unzip
          wget

    - name: List files for debugging
      run: |
            ls -R Clases/GUI

    - name: "Compile project with Allegro 4.4.2 (static)"
      shell: msys2 {0}
      run: |
            set -e
            wget -q http://cdn.allegro.cc/file/library/allegro/4.4.2/allegro-4.4.2-mingw-4.5.2.zip
            unzip -q allegro-4.4.2-mingw-4.5.2.zip

    - name: Build with make in Clases/GUI
      shell: msys2 {0}
      run: |
            export PATH=/c/msys64/mingw32/bin:$PATH
            which g++
            g++ --version
            cd Clases/GUI
            make allegro
            make sdl

    - name: "Package clean ZIP"
      shell: msys2 {0}
      run: |
            cd Clases/GUI
            dlls=$(for f in libgcc_s_dw2-1.dll libstdc++-6.dll SDL2_ttf.dll SDL2.dll libwinpthread-1.dll libfreetype-6.dll libharfbuzz-0.dll libbrotlidec.dll libbz2-1.dll libpng16-16.dll libgraphite2.dll libglib-2.0-0.dll libbrotlicommon.dll libintl-8.dll libpcre2-8-0.dll libiconv-2.dll zlib1.dll; do whereis $f | awk -F: '{print $2}' | xargs; done)
            pacman -Sy --noconfirm zip
            zip -r9 -j ../../Win32-MinGw-build-test.zip ./testAllegro.exe ../../Extras/prueba-font.pcx ./testSDL.exe $dlls
            sha256sum ../../Win32-MinGw-build-test.zip > ../../Win32-MinGw-build-test.sha256
            echo "ZIP and hash created:"
            ls -lh ../../Win32-MinGw-build-test*

    - name: "Upload ZIP artifact"
      uses: actions/upload-artifact@v4
      with:
          name: Win32-MinGw-build-test
          path: |
            Win32-MinGw-build-test.zip
            Win32-MinGw-build-test.sha256


