name: 'test'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install -y build-essential liballegro4-dev
    - name: Build and install juegocpp
      run: |
        cd Clases
        make
        make install
        cd ..
        mkdir juegocpp
        mv Extras/juegocpp juegocpp/
    - uses: actions/upload-artifact@master
      with:
        name: juegocpp
        path: juegocpp
